//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Dom_i_rachunki {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Dom_i_rachunki"]));
            }
            set {
                this["Dom_i_rachunki"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Wydatki_podstawowe {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Wydatki_podstawowe"]));
            }
            set {
                this["Wydatki_podstawowe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Finanse {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Finanse"]));
            }
            set {
                this["Finanse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Rozrywka_i_podróże {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Rozrywka_i_podróże"]));
            }
            set {
                this["Rozrywka_i_podróże"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Samochód_i_transport {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Samochód_i_transport"]));
            }
            set {
                this["Samochód_i_transport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Edukacja {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Edukacja"]));
            }
            set {
                this["Edukacja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Odzież_i_obuwie {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Odzież_i_obuwie"]));
            }
            set {
                this["Odzież_i_obuwie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Zdrowie_i_Uroda {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Zdrowie_i_Uroda"]));
            }
            set {
                this["Zdrowie_i_Uroda"] = value;
            }
        }
    }
}
